### ISSUE TITLE
Move from Glog v0.3.5 to something newer

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/aditof_sdk#802]
Glog v3.5.0 no longer builds on Ubuntu 22.04. It fails to build some unittests. There is no cmake option to deactivate them. So we have to move to a newer version of glog.

Compilation error message was:
```[ 40%] Building CXX object CMakeFiles/logging_unittest.dir/src/logging_unittest.cc.o

In file included from /home/dan/repos/glog/src/logging_unittest.cc:58:

/home/dan/repos/glog/src/googletest.h:579:33: error: ISO C++17 does not allow dynamic exception specifications

  579 | void* operator new(size_t size) throw(std::bad_alloc) {

      |                                 ^~~~~

/home/dan/repos/glog/src/googletest.h:586:35: error: ISO C++17 does not allow dynamic exception specifications

  586 | void* operator new[](size_t size) throw(std::bad_alloc) {
```
